### PR TITLE
Let auth use motw and hotd in bot PMs

### PR DESCRIPTION
**Pull request by Aurolux**
- gets spammy in the chat

### CODE REVIEW

**Comment by HarmanPC** [comment]
That is added so people don't use it in writing, you can add a condition so we can only use it in canalave library OR in PMs.

**Comment by HarmanPC** [comment]
Also, I'm adding that in https://github.com/AxeBane/The-Scribe/pull/14

**Comment by Aurolux** [comment]
Okay, I'll close this PR once your done adding that it. @HarmanPC just let me know

**Comment by HarmanPC** [comment]
I added that @Aurolux

**Pull request closed without merging**
